apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: repo.treescale.com/godikadze/{{ .Values.service.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
          env:
            - name: ENV
              value: "production"
          resources:
            requests:
              cpu: 150m
            limits:
              cpu: 300m
      imagePullSecrets:
        - name: treescale-auth